apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: bigblueswarm
spec:
  clusterIP: None
  ports:
    - port: 8086
      targetPort: 8086
      name: influxdb
  selector:
    app: influxdb
