apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv
  namespace: bigblueswarm
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data"
